name: new_comment_digest
on:
  schedule:  # 08:30 daily
    - cron: '30 8 * * *'
  workflow_dispatch:  # This job can also be run on-demand (is this needed?)
permissions:
  contents: read  # Is this needed?

jobs:
  new_comment_digeste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@4
        with:
          python-version: 3.x
      - run: pip install requests
      - run: scripts/gh_scripts/issue_comment_bot.py 24 "$SLACK_CHANNEL" "$SLACK_TOKEN"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ABC_TEAM_PLUS }}
