name: publish_storybook
on:
  push:
    branches:
      - master
    paths:
      - 'stories/**'

jobs:
  publish_storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
        npm ci
        git pull origin master
        git checkout origin storybook
        git rebase master
        npm run build-storybook
        git add .
        git commit -m "Generated storybook site"

